# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 01:15
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160127_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=blog.models.PhoneField(blank=True, max_length=20),
        ),
    ]
